apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: orderflow/api-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: ORDER_SERVICE_URL
              value: http://order-service:8001
            - name: JWT_SECRET
              value: "jwt-secret-do-not-share-2024"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
